project:
  type: website
  output-dir: "docs"

website:
  title: "Empirical guide to analyzing Wisconsin Election Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - ReportingUnitsVsWards.qmd
      - RegisteredVoters.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



