---
format: 
  html:
    code-fold: true
    code-summary: "Show the code"
title: "Registered Voters"
reference-location: margin
citation-location: margin
---

Tracking registered voters is useful for measuring voter participation, but several aspects of Wisconsin election administration complicate its use.

## Ward files

For one, the most frequently updated registered voter statistics are published at the ward, not reporting-unit level. These ward-level files are [published by the Wisconsin Election Commission](https://elections.wi.gov/statistics-data/voter-registration-statistics) showing totals usually on the first day of each month.

This ward-level data runs into the same caveats described in the previous section. To directly compare these numbers with election results, you would first need to aggregate the wards into the reporting units used in that specific election. Ward boundaries can change in ways that make these comparisons difficult or impossible.

Another problem is that none of the monthly registered voter files *directly* correspond to the Election Day universe of registered voters, as none of Wisconsin's various election days falls on the first of a month. Moreover, Wisconsin still maintains same-day registration. You can show up at your local polling place, register, and immediately cast a ballot. As a result, many wards end election day with more registered voters than they began it with. In places with a highly transient population, like college campuses, the number of election day registrants can be very high.

Also, the state's registration system works hard to *transfer* the identify of registered voters when they move within the state. If you are registered in Oshkosh, move to Appleton, and then register at your new polling place on Election Day, the state will transfer your old voter registration in their database. This prevents an individual voter from being registered in two places at once. It also means that same day registration can actually *reduce* the number of registered voters in a ward versus what it held entering election day.

For all these reasons, it's better to use the registered voter file from the first day of the month *following* the election than it is from the first day of the month containing the election day.

## Reporting Unit election reports

The WEC also [publishes another file](https://elections.wi.gov/statistics-data/voting-statistics) of detailed election statistics recorded at the reporting unit level. Formerly called the EL-190 report, it includes 3 voter registration columns.

  *   Open Registrants - includes everybody who was registered to vote in that reporting unit after the last election or who registered prior to the 19th day before the current election.
  *   Late Registrants - includes those who registered to vote from the 19th prior to the election through the last Friday before the election. No one in Wisconsin can register to vote on the Saturday, Sunday, or Monday before the election on Tuesday. I believe this rule is to give administrators time to print the voter rolls for each ward.
  *   Election Day Registrants - includes everybody who registers to vote on election day
  
By adding these three columns, you can get a figure of total registered voters for each reporting unit which includes election day registrants.

